/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createValidateResponseFromDiscriminatorValue, type ValidateResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Auth/validate
 */
export interface ValidateRequestBuilder extends BaseRequestBuilder<ValidateRequestBuilder> {
    /**
     * Validates the current user's session.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ValidateResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ValidateResponse | undefined>;
    /**
     * Validates the current user's session.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ValidateRequestBuilderUriTemplate = "{+baseurl}/api/Auth/validate";
/**
 * Metadata for all the requests in the request builder.
 */
export const ValidateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ValidateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createValidateResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
