"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlaceRequestBuilderRequestsMetadata = exports.PlaceRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const index_js_1 = require("../../../models/index.js");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
/**
 * Uri template for the request builder.
 */
exports.PlaceRequestBuilderUriTemplate = "{+baseurl}/api/Order/place";
/**
 * Metadata for all the requests in the request builder.
 */
exports.PlaceRequestBuilderRequestsMetadata = {
    post: {
        uriTemplate: exports.PlaceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory: index_js_1.createPlaceOrderResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: index_js_1.serializePlaceOrderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map