/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPlaceOrderResponseFromDiscriminatorValue, serializePlaceOrderRequest, serializePlaceOrderResponse, type PlaceOrderRequest, type PlaceOrderResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Order/place
 */
export interface PlaceRequestBuilder extends BaseRequestBuilder<PlaceRequestBuilder> {
    /**
     * Places a new order based on the provided request.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PlaceOrderResponse>}
     */
     post(body: PlaceOrderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PlaceOrderResponse | undefined>;
    /**
     * Places a new order based on the provided request.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PlaceOrderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PlaceRequestBuilderUriTemplate = "{+baseurl}/api/Order/place";
/**
 * Metadata for all the requests in the request builder.
 */
export const PlaceRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PlaceRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPlaceOrderResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePlaceOrderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
