"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrderRequestBuilderNavigationMetadata = exports.OrderRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const index_js_1 = require("./cancel/index.js");
// @ts-ignore
const index_js_2 = require("./modify/index.js");
// @ts-ignore
const index_js_3 = require("./place/index.js");
// @ts-ignore
const index_js_4 = require("./search/index.js");
// @ts-ignore
const index_js_5 = require("./searchOpen/index.js");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
/**
 * Uri template for the request builder.
 */
exports.OrderRequestBuilderUriTemplate = "{+baseurl}/api/Order";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.OrderRequestBuilderNavigationMetadata = {
    cancel: {
        requestsMetadata: index_js_1.CancelRequestBuilderRequestsMetadata,
    },
    modify: {
        requestsMetadata: index_js_2.ModifyRequestBuilderRequestsMetadata,
    },
    place: {
        requestsMetadata: index_js_3.PlaceRequestBuilderRequestsMetadata,
    },
    search: {
        requestsMetadata: index_js_4.SearchRequestBuilderRequestsMetadata,
    },
    searchOpen: {
        requestsMetadata: index_js_5.SearchOpenRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map