// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OpenAPI.Api.Order.Cancel;
using OpenAPI.Api.Order.Modify;
using OpenAPI.Api.Order.Place;
using OpenAPI.Api.Order.Search;
using OpenAPI.Api.Order.SearchOpen;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OpenAPI.Api.Order
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Order
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrderRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::OpenAPI.Api.Order.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::OpenAPI.Api.Order.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The modify property</summary>
        public global::OpenAPI.Api.Order.Modify.ModifyRequestBuilder Modify
        {
            get => new global::OpenAPI.Api.Order.Modify.ModifyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The place property</summary>
        public global::OpenAPI.Api.Order.Place.PlaceRequestBuilder Place
        {
            get => new global::OpenAPI.Api.Order.Place.PlaceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::OpenAPI.Api.Order.Search.SearchRequestBuilder Search
        {
            get => new global::OpenAPI.Api.Order.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchOpen property</summary>
        public global::OpenAPI.Api.Order.SearchOpen.SearchOpenRequestBuilder SearchOpen
        {
            get => new global::OpenAPI.Api.Order.SearchOpen.SearchOpenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Api.Order.OrderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Order", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Api.Order.OrderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Order", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
