// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OpenAPI.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ModifyOrderRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountId property</summary>
        public int? AccountId { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The limitPrice property</summary>
        public decimal? LimitPrice { get; set; }
        /// <summary>The orderId property</summary>
        public long? OrderId { get; set; }
        /// <summary>The size property</summary>
        public int? Size { get; set; }
        /// <summary>The stopPrice property</summary>
        public decimal? StopPrice { get; set; }
        /// <summary>The trailPrice property</summary>
        public decimal? TrailPrice { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Models.ModifyOrderRequest"/> and sets the default values.
        /// </summary>
        public ModifyOrderRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OpenAPI.Models.ModifyOrderRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OpenAPI.Models.ModifyOrderRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::OpenAPI.Models.ModifyOrderRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetIntValue(); } },
                { "limitPrice", n => { LimitPrice = n.GetDecimalValue(); } },
                { "orderId", n => { OrderId = n.GetLongValue(); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "stopPrice", n => { StopPrice = n.GetDecimalValue(); } },
                { "trailPrice", n => { TrailPrice = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accountId", AccountId);
            writer.WriteDecimalValue("limitPrice", LimitPrice);
            writer.WriteLongValue("orderId", OrderId);
            writer.WriteIntValue("size", Size);
            writer.WriteDecimalValue("stopPrice", StopPrice);
            writer.WriteDecimalValue("trailPrice", TrailPrice);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
