/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createClosePositionResponseFromDiscriminatorValue, serializeCloseContractPositionRequest, serializeClosePositionResponse, type CloseContractPositionRequest, type ClosePositionResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Position/closeContract
 */
export interface CloseContractRequestBuilder extends BaseRequestBuilder<CloseContractRequestBuilder> {
    /**
     * Closes a contract position based on the provided request.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ClosePositionResponse>}
     */
     post(body: CloseContractPositionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ClosePositionResponse | undefined>;
    /**
     * Closes a contract position based on the provided request.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CloseContractPositionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CloseContractRequestBuilderUriTemplate = "{+baseurl}/api/Position/closeContract";
/**
 * Metadata for all the requests in the request builder.
 */
export const CloseContractRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CloseContractRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createClosePositionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCloseContractPositionRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
