"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthRequestBuilderNavigationMetadata = exports.AuthRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const index_js_1 = require("./loginApp/index.js");
// @ts-ignore
const index_js_2 = require("./loginKey/index.js");
// @ts-ignore
const index_js_3 = require("./logout/index.js");
// @ts-ignore
const index_js_4 = require("./validate/index.js");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
/**
 * Uri template for the request builder.
 */
exports.AuthRequestBuilderUriTemplate = "{+baseurl}/api/Auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.AuthRequestBuilderNavigationMetadata = {
    loginApp: {
        requestsMetadata: index_js_1.LoginAppRequestBuilderRequestsMetadata,
    },
    loginKey: {
        requestsMetadata: index_js_2.LoginKeyRequestBuilderRequestsMetadata,
    },
    logout: {
        requestsMetadata: index_js_3.LogoutRequestBuilderRequestsMetadata,
    },
    validate: {
        requestsMetadata: index_js_4.ValidateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map