/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LoginAppRequestBuilderRequestsMetadata, type LoginAppRequestBuilder } from './loginApp/index.js';
// @ts-ignore
import { LoginKeyRequestBuilderRequestsMetadata, type LoginKeyRequestBuilder } from './loginKey/index.js';
// @ts-ignore
import { LogoutRequestBuilderRequestsMetadata, type LogoutRequestBuilder } from './logout/index.js';
// @ts-ignore
import { type ValidateRequestBuilder, ValidateRequestBuilderRequestsMetadata } from './validate/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The loginApp property
     */
    get loginApp(): LoginAppRequestBuilder;
    /**
     * The loginKey property
     */
    get loginKey(): LoginKeyRequestBuilder;
    /**
     * The logout property
     */
    get logout(): LogoutRequestBuilder;
    /**
     * The validate property
     */
    get validate(): ValidateRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/api/Auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    loginApp: {
        requestsMetadata: LoginAppRequestBuilderRequestsMetadata,
    },
    loginKey: {
        requestsMetadata: LoginKeyRequestBuilderRequestsMetadata,
    },
    logout: {
        requestsMetadata: LogoutRequestBuilderRequestsMetadata,
    },
    validate: {
        requestsMetadata: ValidateRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
