/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSearchOrderResponseFromDiscriminatorValue, serializeSearchOpenOrderRequest, serializeSearchOrderResponse, type SearchOpenOrderRequest, type SearchOrderResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Order/searchOpen
 */
export interface SearchOpenRequestBuilder extends BaseRequestBuilder<SearchOpenRequestBuilder> {
    /**
     * Searches for open (working/active) orders based on the provided request.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SearchOrderResponse>}
     */
     post(body: SearchOpenOrderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SearchOrderResponse | undefined>;
    /**
     * Searches for open (working/active) orders based on the provided request.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SearchOpenOrderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SearchOpenRequestBuilderUriTemplate = "{+baseurl}/api/Order/searchOpen";
/**
 * Metadata for all the requests in the request builder.
 */
export const SearchOpenRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SearchOpenRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createSearchOrderResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSearchOpenOrderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
