/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPartialClosePositionResponseFromDiscriminatorValue, serializePartialCloseContractPositionRequest, serializePartialClosePositionResponse, type PartialCloseContractPositionRequest, type PartialClosePositionResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Position/partialCloseContract
 */
export interface PartialCloseContractRequestBuilder extends BaseRequestBuilder<PartialCloseContractRequestBuilder> {
    /**
     * Partially closes a contract position based on the provided request.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PartialClosePositionResponse>}
     */
     post(body: PartialCloseContractPositionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PartialClosePositionResponse | undefined>;
    /**
     * Partially closes a contract position based on the provided request.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PartialCloseContractPositionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PartialCloseContractRequestBuilderUriTemplate = "{+baseurl}/api/Position/partialCloseContract";
/**
 * Metadata for all the requests in the request builder.
 */
export const PartialCloseContractRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PartialCloseContractRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createPartialClosePositionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePartialCloseContractPositionRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
