// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OpenAPI.Api.Auth.LoginApp;
using OpenAPI.Api.Auth.LoginKey;
using OpenAPI.Api.Auth.Logout;
using OpenAPI.Api.Auth.Validate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OpenAPI.Api.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The loginApp property</summary>
        public global::OpenAPI.Api.Auth.LoginApp.LoginAppRequestBuilder LoginApp
        {
            get => new global::OpenAPI.Api.Auth.LoginApp.LoginAppRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The loginKey property</summary>
        public global::OpenAPI.Api.Auth.LoginKey.LoginKeyRequestBuilder LoginKey
        {
            get => new global::OpenAPI.Api.Auth.LoginKey.LoginKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::OpenAPI.Api.Auth.Logout.LogoutRequestBuilder Logout
        {
            get => new global::OpenAPI.Api.Auth.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validate property</summary>
        public global::OpenAPI.Api.Auth.Validate.ValidateRequestBuilder Validate
        {
            get => new global::OpenAPI.Api.Auth.Validate.ValidateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Api.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Api.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
