"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StatusRequestBuilderNavigationMetadata = exports.StatusRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const index_js_1 = require("./ping/index.js");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
/**
 * Uri template for the request builder.
 */
exports.StatusRequestBuilderUriTemplate = "{+baseurl}/api/Status";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.StatusRequestBuilderNavigationMetadata = {
    ping: {
        requestsMetadata: index_js_1.PingRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map