// <auto-generated/>
#pragma warning disable CS0618
using Kiota.Api.Position.CloseContract;
using Kiota.Api.Position.PartialCloseContract;
using Kiota.Api.Position.SearchOpen;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kiota.Api.Position
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Position
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PositionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The closeContract property</summary>
        public global::Kiota.Api.Position.CloseContract.CloseContractRequestBuilder CloseContract
        {
            get => new global::Kiota.Api.Position.CloseContract.CloseContractRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partialCloseContract property</summary>
        public global::Kiota.Api.Position.PartialCloseContract.PartialCloseContractRequestBuilder PartialCloseContract
        {
            get => new global::Kiota.Api.Position.PartialCloseContract.PartialCloseContractRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The searchOpen property</summary>
        public global::Kiota.Api.Position.SearchOpen.SearchOpenRequestBuilder SearchOpen
        {
            get => new global::Kiota.Api.Position.SearchOpen.SearchOpenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kiota.Api.Position.PositionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PositionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Position", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kiota.Api.Position.PositionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PositionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Position", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
