"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogoutRequestBuilderRequestsMetadata = exports.LogoutRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const index_js_1 = require("../../../models/index.js");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
/**
 * Uri template for the request builder.
 */
exports.LogoutRequestBuilderUriTemplate = "{+baseurl}/api/Auth/logout";
/**
 * Metadata for all the requests in the request builder.
 */
exports.LogoutRequestBuilderRequestsMetadata = {
    post: {
        uriTemplate: exports.LogoutRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory: index_js_1.createLogoutResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map