"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ContractRequestBuilderNavigationMetadata = exports.ContractRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const index_js_1 = require("./available/index.js");
// @ts-ignore
const index_js_2 = require("./search/index.js");
// @ts-ignore
const index_js_3 = require("./searchById/index.js");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
/**
 * Uri template for the request builder.
 */
exports.ContractRequestBuilderUriTemplate = "{+baseurl}/api/Contract";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.ContractRequestBuilderNavigationMetadata = {
    available: {
        requestsMetadata: index_js_1.AvailableRequestBuilderRequestsMetadata,
    },
    search: {
        requestsMetadata: index_js_2.SearchRequestBuilderRequestsMetadata,
    },
    searchById: {
        requestsMetadata: index_js_3.SearchByIdRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map