// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OpenAPI.Api.Trade.Search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OpenAPI.Api.Trade
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Trade
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TradeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The search property</summary>
        public global::OpenAPI.Api.Trade.Search.SearchRequestBuilder Search
        {
            get => new global::OpenAPI.Api.Trade.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Api.Trade.TradeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TradeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Trade", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Api.Trade.TradeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TradeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Trade", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
