// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using System.Collections.Generic;
using System.IO;
using System;
namespace Topstep.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ModifyOrderRequest : IAdditionalDataHolder, IBackedModel, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountId property</summary>
        public int? AccountId
        {
            get { return BackingStore?.Get<int?>("accountId"); }
            set { BackingStore?.Set("accountId", value); }
        }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData
        {
            get { return BackingStore.Get<IDictionary<string, object>>("AdditionalData") ?? new Dictionary<string, object>(); }
            set { BackingStore.Set("AdditionalData", value); }
        }
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The limitPrice property</summary>
        public decimal? LimitPrice
        {
            get { return BackingStore?.Get<decimal?>("limitPrice"); }
            set { BackingStore?.Set("limitPrice", value); }
        }
        /// <summary>The orderId property</summary>
        public long? OrderId
        {
            get { return BackingStore?.Get<long?>("orderId"); }
            set { BackingStore?.Set("orderId", value); }
        }
        /// <summary>The size property</summary>
        public int? Size
        {
            get { return BackingStore?.Get<int?>("size"); }
            set { BackingStore?.Set("size", value); }
        }
        /// <summary>The stopPrice property</summary>
        public decimal? StopPrice
        {
            get { return BackingStore?.Get<decimal?>("stopPrice"); }
            set { BackingStore?.Set("stopPrice", value); }
        }
        /// <summary>The trailPrice property</summary>
        public decimal? TrailPrice
        {
            get { return BackingStore?.Get<decimal?>("trailPrice"); }
            set { BackingStore?.Set("trailPrice", value); }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Topstep.Api.Models.ModifyOrderRequest"/> and sets the default values.
        /// </summary>
        public ModifyOrderRequest()
        {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Topstep.Api.Models.ModifyOrderRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Topstep.Api.Models.ModifyOrderRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Topstep.Api.Models.ModifyOrderRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountId", n => { AccountId = n.GetIntValue(); } },
                { "limitPrice", n => { LimitPrice = n.GetDecimalValue(); } },
                { "orderId", n => { OrderId = n.GetLongValue(); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "stopPrice", n => { StopPrice = n.GetDecimalValue(); } },
                { "trailPrice", n => { TrailPrice = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accountId", AccountId);
            writer.WriteDecimalValue("limitPrice", LimitPrice);
            writer.WriteLongValue("orderId", OrderId);
            writer.WriteIntValue("size", Size);
            writer.WriteDecimalValue("stopPrice", StopPrice);
            writer.WriteDecimalValue("trailPrice", TrailPrice);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
