/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLoginResponseFromDiscriminatorValue, serializeLoginApiKeyRequest, serializeLoginResponse, type LoginApiKeyRequest, type LoginResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Auth/loginKey
 */
export interface LoginKeyRequestBuilder extends BaseRequestBuilder<LoginKeyRequestBuilder> {
    /**
     * Login as the specified user using the specified API key.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LoginResponse>}
     */
     post(body: LoginApiKeyRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LoginResponse | undefined>;
    /**
     * Login as the specified user using the specified API key.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: LoginApiKeyRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LoginKeyRequestBuilderUriTemplate = "{+baseurl}/api/Auth/loginKey";
/**
 * Metadata for all the requests in the request builder.
 */
export const LoginKeyRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: LoginKeyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createLoginResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLoginApiKeyRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
