/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RetrieveBarsRequestBuilderRequestsMetadata, type RetrieveBarsRequestBuilder } from './retrieveBars/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/History
 */
export interface HistoryRequestBuilder extends BaseRequestBuilder<HistoryRequestBuilder> {
    /**
     * The retrieveBars property
     */
    get retrieveBars(): RetrieveBarsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const HistoryRequestBuilderUriTemplate = "{+baseurl}/api/History";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HistoryRequestBuilderNavigationMetadata: Record<Exclude<keyof HistoryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    retrieveBars: {
        requestsMetadata: RetrieveBarsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
