"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiClientNavigationMetadata = exports.ApiClientUriTemplate = void 0;
exports.createApiClient = createApiClient;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const index_js_1 = require("./api/index.js");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
// @ts-ignore
const kiota_serialization_form_1 = require("@microsoft/kiota-serialization-form");
// @ts-ignore
const kiota_serialization_json_1 = require("@microsoft/kiota-serialization-json");
// @ts-ignore
const kiota_serialization_multipart_1 = require("@microsoft/kiota-serialization-multipart");
// @ts-ignore
const kiota_serialization_text_1 = require("@microsoft/kiota-serialization-text");
/**
 * Instantiates a new {@link ApiClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
function createApiClient(requestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory();
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory();
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
        parseNodeFactoryRegistry.registerDefaultDeserializer(kiota_serialization_json_1.JsonParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(kiota_serialization_text_1.TextParseNodeFactory, backingStoreFactory);
        parseNodeFactoryRegistry.registerDefaultDeserializer(kiota_serialization_form_1.FormParseNodeFactory, backingStoreFactory);
    }
    if (serializationWriterFactory.registerDefaultSerializer) {
        serializationWriterFactory.registerDefaultSerializer(kiota_serialization_json_1.JsonSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(kiota_serialization_text_1.TextSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(kiota_serialization_form_1.FormSerializationWriterFactory);
        serializationWriterFactory.registerDefaultSerializer(kiota_serialization_multipart_1.MultipartSerializationWriterFactory);
    }
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://api.topstepx.com";
    }
    const pathParameters = {
        "baseurl": requestAdapter.baseUrl,
    };
    return (0, kiota_abstractions_1.apiClientProxifier)(requestAdapter, pathParameters, exports.ApiClientNavigationMetadata, undefined);
}
/**
 * Uri template for the request builder.
 */
exports.ApiClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.ApiClientNavigationMetadata = {
    api: {
        navigationMetadata: index_js_1.ApiRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=apiClient.js.map