// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPI.Client;

namespace OpenAPI.Model
{
    /// <summary>
    /// 0 &#x3D; Success 1 &#x3D; AccountNotFound 2 &#x3D; OrderNotFound 3 &#x3D; Rejected 4 &#x3D; Pending 5 &#x3D; UnknownError 6 &#x3D; AccountRejected
    /// </summary>
    /// <value>0 &#x3D; Success 1 &#x3D; AccountNotFound 2 &#x3D; OrderNotFound 3 &#x3D; Rejected 4 &#x3D; Pending 5 &#x3D; UnknownError 6 &#x3D; AccountRejected</value>
    public enum CancelOrderErrorCode
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        NUMBER_0 = 0,

        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        NUMBER_1 = 1,

        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        NUMBER_2 = 2,

        /// <summary>
        /// Enum NUMBER_3 for value: 3
        /// </summary>
        NUMBER_3 = 3,

        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        NUMBER_4 = 4,

        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        NUMBER_5 = 5,

        /// <summary>
        /// Enum NUMBER_6 for value: 6
        /// </summary>
        NUMBER_6 = 6
    }

    /// <summary>
    /// Converts <see cref="CancelOrderErrorCode"/> to and from the JSON value
    /// </summary>
    public static class CancelOrderErrorCodeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="CancelOrderErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CancelOrderErrorCode FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return CancelOrderErrorCode.NUMBER_0;

            if (value.Equals((1).ToString()))
                return CancelOrderErrorCode.NUMBER_1;

            if (value.Equals((2).ToString()))
                return CancelOrderErrorCode.NUMBER_2;

            if (value.Equals((3).ToString()))
                return CancelOrderErrorCode.NUMBER_3;

            if (value.Equals((4).ToString()))
                return CancelOrderErrorCode.NUMBER_4;

            if (value.Equals((5).ToString()))
                return CancelOrderErrorCode.NUMBER_5;

            if (value.Equals((6).ToString()))
                return CancelOrderErrorCode.NUMBER_6;

            throw new NotImplementedException($"Could not convert value to type CancelOrderErrorCode: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="CancelOrderErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static CancelOrderErrorCode? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return CancelOrderErrorCode.NUMBER_0;

            if (value.Equals((1).ToString()))
                return CancelOrderErrorCode.NUMBER_1;

            if (value.Equals((2).ToString()))
                return CancelOrderErrorCode.NUMBER_2;

            if (value.Equals((3).ToString()))
                return CancelOrderErrorCode.NUMBER_3;

            if (value.Equals((4).ToString()))
                return CancelOrderErrorCode.NUMBER_4;

            if (value.Equals((5).ToString()))
                return CancelOrderErrorCode.NUMBER_5;

            if (value.Equals((6).ToString()))
                return CancelOrderErrorCode.NUMBER_6;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="CancelOrderErrorCode"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(CancelOrderErrorCode value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CancelOrderErrorCode"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class CancelOrderErrorCodeJsonConverter : JsonConverter<CancelOrderErrorCode>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CancelOrderErrorCode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CancelOrderErrorCode? result = rawValue == null
                ? null
                : CancelOrderErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CancelOrderErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cancelOrderErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CancelOrderErrorCode cancelOrderErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(CancelOrderErrorCodeValueConverter.ToJsonValue(cancelOrderErrorCode).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CancelOrderErrorCode"/>
    /// </summary>
    public class CancelOrderErrorCodeNullableJsonConverter : JsonConverter<CancelOrderErrorCode?>
    {
        /// <summary>
        /// Returns a CancelOrderErrorCode from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override CancelOrderErrorCode? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            CancelOrderErrorCode? result = rawValue == null
                ? null
                : CancelOrderErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the CancelOrderErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cancelOrderErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, CancelOrderErrorCode? cancelOrderErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(cancelOrderErrorCode.HasValue ? CancelOrderErrorCodeValueConverter.ToJsonValue(cancelOrderErrorCode.Value).ToString() : "null");
        }
    }
}
