// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPI.Client;

namespace OpenAPI.Model
{
    /// <summary>
    /// 0 &#x3D; Success
    /// </summary>
    /// <value>0 &#x3D; Success</value>
    public enum ListAvailableContractErrorCode
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        NUMBER_0 = 0
    }

    /// <summary>
    /// Converts <see cref="ListAvailableContractErrorCode"/> to and from the JSON value
    /// </summary>
    public static class ListAvailableContractErrorCodeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ListAvailableContractErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ListAvailableContractErrorCode FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return ListAvailableContractErrorCode.NUMBER_0;

            throw new NotImplementedException($"Could not convert value to type ListAvailableContractErrorCode: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ListAvailableContractErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ListAvailableContractErrorCode? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return ListAvailableContractErrorCode.NUMBER_0;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ListAvailableContractErrorCode"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(ListAvailableContractErrorCode value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListAvailableContractErrorCode"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ListAvailableContractErrorCodeJsonConverter : JsonConverter<ListAvailableContractErrorCode>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ListAvailableContractErrorCode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ListAvailableContractErrorCode? result = rawValue == null
                ? null
                : ListAvailableContractErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ListAvailableContractErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listAvailableContractErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ListAvailableContractErrorCode listAvailableContractErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(ListAvailableContractErrorCodeValueConverter.ToJsonValue(listAvailableContractErrorCode).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListAvailableContractErrorCode"/>
    /// </summary>
    public class ListAvailableContractErrorCodeNullableJsonConverter : JsonConverter<ListAvailableContractErrorCode?>
    {
        /// <summary>
        /// Returns a ListAvailableContractErrorCode from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ListAvailableContractErrorCode? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ListAvailableContractErrorCode? result = rawValue == null
                ? null
                : ListAvailableContractErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ListAvailableContractErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listAvailableContractErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ListAvailableContractErrorCode? listAvailableContractErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(listAvailableContractErrorCode.HasValue ? ListAvailableContractErrorCodeValueConverter.ToJsonValue(listAvailableContractErrorCode.Value).ToString() : "null");
        }
    }
}
