// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenApi.Client;

namespace OpenApi.Model
{
    /// <summary>
    /// LoginResponse
    /// </summary>
    public partial class LoginResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginResponse" /> class.
        /// </summary>
        /// <param name="success">success</param>
        /// <param name="errorCode">errorCode</param>
        /// <param name="errorMessage">errorMessage</param>
        /// <param name="token">token</param>
        [JsonConstructor]
        public LoginResponse(bool success, LoginErrorCode errorCode, Option<string?> errorMessage = default, Option<string?> token = default)
        {
            Success = success;
            ErrorCode = errorCode;
            ErrorMessageOption = errorMessage;
            TokenOption = token;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [JsonPropertyName("errorCode")]
        public LoginErrorCode ErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        /// <summary>
        /// Used to track the state of ErrorMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [JsonPropertyName("errorMessage")]
        public string? ErrorMessage { get { return this.ErrorMessageOption; } set { this.ErrorMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Token
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TokenOption { get; private set; }

        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        [JsonPropertyName("token")]
        public string? Token { get { return this.TokenOption; } set { this.TokenOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoginResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LoginResponse" />
    /// </summary>
    public class LoginResponseJsonConverter : JsonConverter<LoginResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="LoginResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LoginResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<LoginErrorCode?> errorCode = default;
            Option<string?> errorMessage = default;
            Option<string?> token = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "errorCode":
                            string? errorCodeRawValue = utf8JsonReader.GetString();
                            if (errorCodeRawValue != null)
                                errorCode = new Option<LoginErrorCode?>(LoginErrorCodeValueConverter.FromStringOrDefault(errorCodeRawValue));
                            break;
                        case "errorMessage":
                            errorMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "token":
                            token = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!success.IsSet)
                throw new ArgumentException("Property is required for class LoginResponse.", nameof(success));

            if (!errorCode.IsSet)
                throw new ArgumentException("Property is required for class LoginResponse.", nameof(errorCode));

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class LoginResponse.");

            if (errorCode.IsSet && errorCode.Value == null)
                throw new ArgumentNullException(nameof(errorCode), "Property is not nullable for class LoginResponse.");

            if (errorMessage.IsSet && errorMessage.Value == null)
                throw new ArgumentNullException(nameof(errorMessage), "Property is not nullable for class LoginResponse.");

            if (token.IsSet && token.Value == null)
                throw new ArgumentNullException(nameof(token), "Property is not nullable for class LoginResponse.");

            return new LoginResponse(success.Value!.Value!, errorCode.Value!.Value!, errorMessage, token);
        }

        /// <summary>
        /// Serializes a <see cref="LoginResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loginResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LoginResponse loginResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, loginResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LoginResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="loginResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LoginResponse loginResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (loginResponse.ErrorMessageOption.IsSet && loginResponse.ErrorMessage == null)
                throw new ArgumentNullException(nameof(loginResponse.ErrorMessage), "Property is required for class LoginResponse.");

            if (loginResponse.TokenOption.IsSet && loginResponse.Token == null)
                throw new ArgumentNullException(nameof(loginResponse.Token), "Property is required for class LoginResponse.");

            writer.WriteBoolean("success", loginResponse.Success);

            var errorCodeRawValue = LoginErrorCodeValueConverter.ToJsonValue(loginResponse.ErrorCode);
            writer.WriteNumber("errorCode", errorCodeRawValue);

            if (loginResponse.ErrorMessageOption.IsSet)
                writer.WriteString("errorMessage", loginResponse.ErrorMessage);

            if (loginResponse.TokenOption.IsSet)
                writer.WriteString("token", loginResponse.Token);
        }
    }
}
