// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPI.Client;

namespace OpenAPI.Model
{
    /// <summary>
    /// 0 &#x3D; None 1 &#x3D; Open 2 &#x3D; Filled 3 &#x3D; Cancelled 4 &#x3D; Expired 5 &#x3D; Rejected 6 &#x3D; Pending 7 &#x3D; PendingCancellation 8 &#x3D; Suspended
    /// </summary>
    /// <value>0 &#x3D; None 1 &#x3D; Open 2 &#x3D; Filled 3 &#x3D; Cancelled 4 &#x3D; Expired 5 &#x3D; Rejected 6 &#x3D; Pending 7 &#x3D; PendingCancellation 8 &#x3D; Suspended</value>
    public enum OrderStatus
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        NUMBER_0 = 0,

        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        NUMBER_1 = 1,

        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        NUMBER_2 = 2,

        /// <summary>
        /// Enum NUMBER_3 for value: 3
        /// </summary>
        NUMBER_3 = 3,

        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        NUMBER_4 = 4,

        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        NUMBER_5 = 5,

        /// <summary>
        /// Enum NUMBER_6 for value: 6
        /// </summary>
        NUMBER_6 = 6,

        /// <summary>
        /// Enum NUMBER_7 for value: 7
        /// </summary>
        NUMBER_7 = 7,

        /// <summary>
        /// Enum NUMBER_8 for value: 8
        /// </summary>
        NUMBER_8 = 8
    }

    /// <summary>
    /// Converts <see cref="OrderStatus"/> to and from the JSON value
    /// </summary>
    public static class OrderStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="OrderStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OrderStatus FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return OrderStatus.NUMBER_0;

            if (value.Equals((1).ToString()))
                return OrderStatus.NUMBER_1;

            if (value.Equals((2).ToString()))
                return OrderStatus.NUMBER_2;

            if (value.Equals((3).ToString()))
                return OrderStatus.NUMBER_3;

            if (value.Equals((4).ToString()))
                return OrderStatus.NUMBER_4;

            if (value.Equals((5).ToString()))
                return OrderStatus.NUMBER_5;

            if (value.Equals((6).ToString()))
                return OrderStatus.NUMBER_6;

            if (value.Equals((7).ToString()))
                return OrderStatus.NUMBER_7;

            if (value.Equals((8).ToString()))
                return OrderStatus.NUMBER_8;

            throw new NotImplementedException($"Could not convert value to type OrderStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="OrderStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OrderStatus? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return OrderStatus.NUMBER_0;

            if (value.Equals((1).ToString()))
                return OrderStatus.NUMBER_1;

            if (value.Equals((2).ToString()))
                return OrderStatus.NUMBER_2;

            if (value.Equals((3).ToString()))
                return OrderStatus.NUMBER_3;

            if (value.Equals((4).ToString()))
                return OrderStatus.NUMBER_4;

            if (value.Equals((5).ToString()))
                return OrderStatus.NUMBER_5;

            if (value.Equals((6).ToString()))
                return OrderStatus.NUMBER_6;

            if (value.Equals((7).ToString()))
                return OrderStatus.NUMBER_7;

            if (value.Equals((8).ToString()))
                return OrderStatus.NUMBER_8;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OrderStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(OrderStatus value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class OrderStatusJsonConverter : JsonConverter<OrderStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override OrderStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            OrderStatus? result = rawValue == null
                ? null
                : OrderStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the OrderStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, OrderStatus orderStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(OrderStatusValueConverter.ToJsonValue(orderStatus).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderStatus"/>
    /// </summary>
    public class OrderStatusNullableJsonConverter : JsonConverter<OrderStatus?>
    {
        /// <summary>
        /// Returns a OrderStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override OrderStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            OrderStatus? result = rawValue == null
                ? null
                : OrderStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the OrderStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, OrderStatus? orderStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(orderStatus.HasValue ? OrderStatusValueConverter.ToJsonValue(orderStatus.Value).ToString() : "null");
        }
    }
}
