// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPI.Client;

namespace OpenAPI.Model
{
    /// <summary>
    /// 0 &#x3D; Success 1 &#x3D; AccountNotFound 2 &#x3D; PositionNotFound 3 &#x3D; ContractNotFound 4 &#x3D; ContractNotActive 5 &#x3D; InvalidCloseSize 6 &#x3D; OrderRejected 7 &#x3D; OrderPending 8 &#x3D; UnknownError 9 &#x3D; AccountRejected
    /// </summary>
    /// <value>0 &#x3D; Success 1 &#x3D; AccountNotFound 2 &#x3D; PositionNotFound 3 &#x3D; ContractNotFound 4 &#x3D; ContractNotActive 5 &#x3D; InvalidCloseSize 6 &#x3D; OrderRejected 7 &#x3D; OrderPending 8 &#x3D; UnknownError 9 &#x3D; AccountRejected</value>
    public enum PartialClosePositionErrorCode
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        NUMBER_0 = 0,

        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        NUMBER_1 = 1,

        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        NUMBER_2 = 2,

        /// <summary>
        /// Enum NUMBER_3 for value: 3
        /// </summary>
        NUMBER_3 = 3,

        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        NUMBER_4 = 4,

        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        NUMBER_5 = 5,

        /// <summary>
        /// Enum NUMBER_6 for value: 6
        /// </summary>
        NUMBER_6 = 6,

        /// <summary>
        /// Enum NUMBER_7 for value: 7
        /// </summary>
        NUMBER_7 = 7,

        /// <summary>
        /// Enum NUMBER_8 for value: 8
        /// </summary>
        NUMBER_8 = 8,

        /// <summary>
        /// Enum NUMBER_9 for value: 9
        /// </summary>
        NUMBER_9 = 9
    }

    /// <summary>
    /// Converts <see cref="PartialClosePositionErrorCode"/> to and from the JSON value
    /// </summary>
    public static class PartialClosePositionErrorCodeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="PartialClosePositionErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PartialClosePositionErrorCode FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return PartialClosePositionErrorCode.NUMBER_0;

            if (value.Equals((1).ToString()))
                return PartialClosePositionErrorCode.NUMBER_1;

            if (value.Equals((2).ToString()))
                return PartialClosePositionErrorCode.NUMBER_2;

            if (value.Equals((3).ToString()))
                return PartialClosePositionErrorCode.NUMBER_3;

            if (value.Equals((4).ToString()))
                return PartialClosePositionErrorCode.NUMBER_4;

            if (value.Equals((5).ToString()))
                return PartialClosePositionErrorCode.NUMBER_5;

            if (value.Equals((6).ToString()))
                return PartialClosePositionErrorCode.NUMBER_6;

            if (value.Equals((7).ToString()))
                return PartialClosePositionErrorCode.NUMBER_7;

            if (value.Equals((8).ToString()))
                return PartialClosePositionErrorCode.NUMBER_8;

            if (value.Equals((9).ToString()))
                return PartialClosePositionErrorCode.NUMBER_9;

            throw new NotImplementedException($"Could not convert value to type PartialClosePositionErrorCode: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="PartialClosePositionErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static PartialClosePositionErrorCode? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return PartialClosePositionErrorCode.NUMBER_0;

            if (value.Equals((1).ToString()))
                return PartialClosePositionErrorCode.NUMBER_1;

            if (value.Equals((2).ToString()))
                return PartialClosePositionErrorCode.NUMBER_2;

            if (value.Equals((3).ToString()))
                return PartialClosePositionErrorCode.NUMBER_3;

            if (value.Equals((4).ToString()))
                return PartialClosePositionErrorCode.NUMBER_4;

            if (value.Equals((5).ToString()))
                return PartialClosePositionErrorCode.NUMBER_5;

            if (value.Equals((6).ToString()))
                return PartialClosePositionErrorCode.NUMBER_6;

            if (value.Equals((7).ToString()))
                return PartialClosePositionErrorCode.NUMBER_7;

            if (value.Equals((8).ToString()))
                return PartialClosePositionErrorCode.NUMBER_8;

            if (value.Equals((9).ToString()))
                return PartialClosePositionErrorCode.NUMBER_9;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="PartialClosePositionErrorCode"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(PartialClosePositionErrorCode value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PartialClosePositionErrorCode"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class PartialClosePositionErrorCodeJsonConverter : JsonConverter<PartialClosePositionErrorCode>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override PartialClosePositionErrorCode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            PartialClosePositionErrorCode? result = rawValue == null
                ? null
                : PartialClosePositionErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the PartialClosePositionErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="partialClosePositionErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, PartialClosePositionErrorCode partialClosePositionErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(PartialClosePositionErrorCodeValueConverter.ToJsonValue(partialClosePositionErrorCode).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PartialClosePositionErrorCode"/>
    /// </summary>
    public class PartialClosePositionErrorCodeNullableJsonConverter : JsonConverter<PartialClosePositionErrorCode?>
    {
        /// <summary>
        /// Returns a PartialClosePositionErrorCode from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override PartialClosePositionErrorCode? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            PartialClosePositionErrorCode? result = rawValue == null
                ? null
                : PartialClosePositionErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the PartialClosePositionErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="partialClosePositionErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, PartialClosePositionErrorCode? partialClosePositionErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(partialClosePositionErrorCode.HasValue ? PartialClosePositionErrorCodeValueConverter.ToJsonValue(partialClosePositionErrorCode.Value).ToString() : "null");
        }
    }
}
