// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenApi.Client;

namespace OpenApi.Model
{
    /// <summary>
    /// PlaceOrderBracket
    /// </summary>
    public partial class PlaceOrderBracket : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlaceOrderBracket" /> class.
        /// </summary>
        /// <param name="ticks">ticks</param>
        /// <param name="type">type</param>
        [JsonConstructor]
        public PlaceOrderBracket(int ticks, OrderType type)
        {
            Ticks = ticks;
            Type = type;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public OrderType Type { get; set; }

        /// <summary>
        /// Gets or Sets Ticks
        /// </summary>
        [JsonPropertyName("ticks")]
        public int Ticks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlaceOrderBracket {\n");
            sb.Append("  Ticks: ").Append(Ticks).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlaceOrderBracket" />
    /// </summary>
    public class PlaceOrderBracketJsonConverter : JsonConverter<PlaceOrderBracket>
    {
        /// <summary>
        /// Deserializes json to <see cref="PlaceOrderBracket" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PlaceOrderBracket Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> ticks = default;
            Option<OrderType?> type = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ticks":
                            ticks = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<OrderType?>(OrderTypeValueConverter.FromStringOrDefault(typeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!ticks.IsSet)
                throw new ArgumentException("Property is required for class PlaceOrderBracket.", nameof(ticks));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class PlaceOrderBracket.", nameof(type));

            if (ticks.IsSet && ticks.Value == null)
                throw new ArgumentNullException(nameof(ticks), "Property is not nullable for class PlaceOrderBracket.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class PlaceOrderBracket.");

            return new PlaceOrderBracket(ticks.Value!.Value!, type.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PlaceOrderBracket" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="placeOrderBracket"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlaceOrderBracket placeOrderBracket, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, placeOrderBracket, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlaceOrderBracket" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="placeOrderBracket"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PlaceOrderBracket placeOrderBracket, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("ticks", placeOrderBracket.Ticks);

            var typeRawValue = OrderTypeValueConverter.ToJsonValue(placeOrderBracket.Type);
            writer.WriteNumber("type", typeRawValue);
        }
    }
}
