// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPI.Client;

namespace OpenAPI.Model
{
    /// <summary>
    /// SearchOrderResponse
    /// </summary>
    public partial class SearchOrderResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchOrderResponse" /> class.
        /// </summary>
        /// <param name="success">success</param>
        /// <param name="errorCode">errorCode</param>
        /// <param name="errorMessage">errorMessage</param>
        /// <param name="orders">orders</param>
        [JsonConstructor]
        public SearchOrderResponse(bool success, SearchOrderErrorCode errorCode, Option<string?> errorMessage = default, Option<List<OrderModel>?> orders = default)
        {
            Success = success;
            ErrorCode = errorCode;
            ErrorMessageOption = errorMessage;
            OrdersOption = orders;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [JsonPropertyName("errorCode")]
        public SearchOrderErrorCode ErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        /// <summary>
        /// Used to track the state of ErrorMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [JsonPropertyName("errorMessage")]
        public string? ErrorMessage { get { return this.ErrorMessageOption; } set { this.ErrorMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Orders
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<OrderModel>?> OrdersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Orders
        /// </summary>
        [JsonPropertyName("orders")]
        public List<OrderModel>? Orders { get { return this.OrdersOption; } set { this.OrdersOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchOrderResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  Orders: ").Append(Orders).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchOrderResponse" />
    /// </summary>
    public class SearchOrderResponseJsonConverter : JsonConverter<SearchOrderResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchOrderResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchOrderResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<SearchOrderErrorCode?> errorCode = default;
            Option<string?> errorMessage = default;
            Option<List<OrderModel>?> orders = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "errorCode":
                            string? errorCodeRawValue = utf8JsonReader.GetString();
                            if (errorCodeRawValue != null)
                                errorCode = new Option<SearchOrderErrorCode?>(SearchOrderErrorCodeValueConverter.FromStringOrDefault(errorCodeRawValue));
                            break;
                        case "errorMessage":
                            errorMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "orders":
                            orders = new Option<List<OrderModel>?>(JsonSerializer.Deserialize<List<OrderModel>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!success.IsSet)
                throw new ArgumentException("Property is required for class SearchOrderResponse.", nameof(success));

            if (!errorCode.IsSet)
                throw new ArgumentException("Property is required for class SearchOrderResponse.", nameof(errorCode));

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class SearchOrderResponse.");

            if (errorCode.IsSet && errorCode.Value == null)
                throw new ArgumentNullException(nameof(errorCode), "Property is not nullable for class SearchOrderResponse.");

            if (errorMessage.IsSet && errorMessage.Value == null)
                throw new ArgumentNullException(nameof(errorMessage), "Property is not nullable for class SearchOrderResponse.");

            if (orders.IsSet && orders.Value == null)
                throw new ArgumentNullException(nameof(orders), "Property is not nullable for class SearchOrderResponse.");

            return new SearchOrderResponse(success.Value!.Value!, errorCode.Value!.Value!, errorMessage, orders);
        }

        /// <summary>
        /// Serializes a <see cref="SearchOrderResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchOrderResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchOrderResponse searchOrderResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, searchOrderResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SearchOrderResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchOrderResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SearchOrderResponse searchOrderResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchOrderResponse.ErrorMessageOption.IsSet && searchOrderResponse.ErrorMessage == null)
                throw new ArgumentNullException(nameof(searchOrderResponse.ErrorMessage), "Property is required for class SearchOrderResponse.");

            if (searchOrderResponse.OrdersOption.IsSet && searchOrderResponse.Orders == null)
                throw new ArgumentNullException(nameof(searchOrderResponse.Orders), "Property is required for class SearchOrderResponse.");

            writer.WriteBoolean("success", searchOrderResponse.Success);

            var errorCodeRawValue = SearchOrderErrorCodeValueConverter.ToJsonValue(searchOrderResponse.ErrorCode);
            writer.WriteNumber("errorCode", errorCodeRawValue);

            if (searchOrderResponse.ErrorMessageOption.IsSet)
                writer.WriteString("errorMessage", searchOrderResponse.ErrorMessage);

            if (searchOrderResponse.OrdersOption.IsSet)
            {
                writer.WritePropertyName("orders");
                JsonSerializer.Serialize(writer, searchOrderResponse.Orders, jsonSerializerOptions);
            }
        }
    }
}
