// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPI.Client;

namespace OpenAPI.Model
{
    /// <summary>
    /// 0 &#x3D; Success 1 &#x3D; AccountNotFound
    /// </summary>
    /// <value>0 &#x3D; Success 1 &#x3D; AccountNotFound</value>
    public enum SearchOrderErrorCode
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        NUMBER_0 = 0,

        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        NUMBER_1 = 1
    }

    /// <summary>
    /// Converts <see cref="SearchOrderErrorCode"/> to and from the JSON value
    /// </summary>
    public static class SearchOrderErrorCodeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SearchOrderErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchOrderErrorCode FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return SearchOrderErrorCode.NUMBER_0;

            if (value.Equals((1).ToString()))
                return SearchOrderErrorCode.NUMBER_1;

            throw new NotImplementedException($"Could not convert value to type SearchOrderErrorCode: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SearchOrderErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchOrderErrorCode? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return SearchOrderErrorCode.NUMBER_0;

            if (value.Equals((1).ToString()))
                return SearchOrderErrorCode.NUMBER_1;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SearchOrderErrorCode"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(SearchOrderErrorCode value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchOrderErrorCode"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SearchOrderErrorCodeJsonConverter : JsonConverter<SearchOrderErrorCode>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchOrderErrorCode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SearchOrderErrorCode? result = rawValue == null
                ? null
                : SearchOrderErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchOrderErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchOrderErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchOrderErrorCode searchOrderErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SearchOrderErrorCodeValueConverter.ToJsonValue(searchOrderErrorCode).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchOrderErrorCode"/>
    /// </summary>
    public class SearchOrderErrorCodeNullableJsonConverter : JsonConverter<SearchOrderErrorCode?>
    {
        /// <summary>
        /// Returns a SearchOrderErrorCode from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchOrderErrorCode? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SearchOrderErrorCode? result = rawValue == null
                ? null
                : SearchOrderErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchOrderErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchOrderErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchOrderErrorCode? searchOrderErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(searchOrderErrorCode.HasValue ? SearchOrderErrorCodeValueConverter.ToJsonValue(searchOrderErrorCode.Value).ToString() : "null");
        }
    }
}
