// <auto-generated>
/*
 * ProjectX Gateway API
 *
 * ProjectX Gateway API Documentation and specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenApi.Client;

namespace OpenApi.Model
{
    /// <summary>
    /// 0 &#x3D; Success 1 &#x3D; AccountNotFound
    /// </summary>
    /// <value>0 &#x3D; Success 1 &#x3D; AccountNotFound</value>
    public enum SearchTradeErrorCode
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        NUMBER_0 = 0,

        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        NUMBER_1 = 1
    }

    /// <summary>
    /// Converts <see cref="SearchTradeErrorCode"/> to and from the JSON value
    /// </summary>
    public static class SearchTradeErrorCodeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SearchTradeErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchTradeErrorCode FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return SearchTradeErrorCode.NUMBER_0;

            if (value.Equals((1).ToString()))
                return SearchTradeErrorCode.NUMBER_1;

            throw new NotImplementedException($"Could not convert value to type SearchTradeErrorCode: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SearchTradeErrorCode"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SearchTradeErrorCode? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return SearchTradeErrorCode.NUMBER_0;

            if (value.Equals((1).ToString()))
                return SearchTradeErrorCode.NUMBER_1;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SearchTradeErrorCode"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(SearchTradeErrorCode value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchTradeErrorCode"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SearchTradeErrorCodeJsonConverter : JsonConverter<SearchTradeErrorCode>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchTradeErrorCode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SearchTradeErrorCode? result = rawValue == null
                ? null
                : SearchTradeErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchTradeErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchTradeErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchTradeErrorCode searchTradeErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SearchTradeErrorCodeValueConverter.ToJsonValue(searchTradeErrorCode).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchTradeErrorCode"/>
    /// </summary>
    public class SearchTradeErrorCodeNullableJsonConverter : JsonConverter<SearchTradeErrorCode?>
    {
        /// <summary>
        /// Returns a SearchTradeErrorCode from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SearchTradeErrorCode? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SearchTradeErrorCode? result = rawValue == null
                ? null
                : SearchTradeErrorCodeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SearchTradeErrorCode to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchTradeErrorCode"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SearchTradeErrorCode? searchTradeErrorCode, JsonSerializerOptions options)
        {
            writer.WriteStringValue(searchTradeErrorCode.HasValue ? SearchTradeErrorCodeValueConverter.ToJsonValue(searchTradeErrorCode.Value).ToString() : "null");
        }
    }
}
