/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CloseContractRequestBuilderRequestsMetadata, type CloseContractRequestBuilder } from './closeContract/index.js';
// @ts-ignore
import { PartialCloseContractRequestBuilderRequestsMetadata, type PartialCloseContractRequestBuilder } from './partialCloseContract/index.js';
// @ts-ignore
import { SearchOpenRequestBuilderRequestsMetadata, type SearchOpenRequestBuilder } from './searchOpen/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Position
 */
export interface PositionRequestBuilder extends BaseRequestBuilder<PositionRequestBuilder> {
    /**
     * The closeContract property
     */
    get closeContract(): CloseContractRequestBuilder;
    /**
     * The partialCloseContract property
     */
    get partialCloseContract(): PartialCloseContractRequestBuilder;
    /**
     * The searchOpen property
     */
    get searchOpen(): SearchOpenRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PositionRequestBuilderUriTemplate = "{+baseurl}/api/Position";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PositionRequestBuilderNavigationMetadata: Record<Exclude<keyof PositionRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    closeContract: {
        requestsMetadata: CloseContractRequestBuilderRequestsMetadata,
    },
    partialCloseContract: {
        requestsMetadata: PartialCloseContractRequestBuilderRequestsMetadata,
    },
    searchOpen: {
        requestsMetadata: SearchOpenRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
