"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PositionRequestBuilderNavigationMetadata = exports.PositionRequestBuilderUriTemplate = void 0;
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
const index_js_1 = require("./closeContract/index.js");
// @ts-ignore
const index_js_2 = require("./partialCloseContract/index.js");
// @ts-ignore
const index_js_3 = require("./searchOpen/index.js");
// @ts-ignore
const kiota_abstractions_1 = require("@microsoft/kiota-abstractions");
/**
 * Uri template for the request builder.
 */
exports.PositionRequestBuilderUriTemplate = "{+baseurl}/api/Position";
/**
 * Metadata for all the navigation properties in the request builder.
 */
exports.PositionRequestBuilderNavigationMetadata = {
    closeContract: {
        requestsMetadata: index_js_1.CloseContractRequestBuilderRequestsMetadata,
    },
    partialCloseContract: {
        requestsMetadata: index_js_2.PartialCloseContractRequestBuilderRequestsMetadata,
    },
    searchOpen: {
        requestsMetadata: index_js_3.SearchOpenRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map