// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OpenAPI.Api.Account;
using OpenAPI.Api.Auth;
using OpenAPI.Api.Contract;
using OpenAPI.Api.History;
using OpenAPI.Api.Order;
using OpenAPI.Api.Position;
using OpenAPI.Api.Status;
using OpenAPI.Api.Trade;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OpenAPI.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Account property</summary>
        public global::OpenAPI.Api.Account.AccountRequestBuilder Account
        {
            get => new global::OpenAPI.Api.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Auth property</summary>
        public global::OpenAPI.Api.Auth.AuthRequestBuilder Auth
        {
            get => new global::OpenAPI.Api.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Contract property</summary>
        public global::OpenAPI.Api.Contract.ContractRequestBuilder Contract
        {
            get => new global::OpenAPI.Api.Contract.ContractRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The History property</summary>
        public global::OpenAPI.Api.History.HistoryRequestBuilder History
        {
            get => new global::OpenAPI.Api.History.HistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Order property</summary>
        public global::OpenAPI.Api.Order.OrderRequestBuilder Order
        {
            get => new global::OpenAPI.Api.Order.OrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Position property</summary>
        public global::OpenAPI.Api.Position.PositionRequestBuilder Position
        {
            get => new global::OpenAPI.Api.Position.PositionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Status property</summary>
        public global::OpenAPI.Api.Status.StatusRequestBuilder Status
        {
            get => new global::OpenAPI.Api.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Trade property</summary>
        public global::OpenAPI.Api.Trade.TradeRequestBuilder Trade
        {
            get => new global::OpenAPI.Api.Trade.TradeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OpenAPI.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
