
//----------------------
// <auto-generated>
//     Generated REST API Client Code Generator v1.32.0.0 on 9/20/2025 1:11:51 AM
//     Using the tool Kiota v1.28.0
// </auto-generated>
//----------------------


